import React from 'react';
import Head from 'next/head';

function MetaData() {
  return (
    <Head>
      <title>Recko - A full stack developer based in Canada</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="../../mylogo.ico" />
    </Head>
  );
}

export default MetaData;
